BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Game] (
    [matchID] INT NOT NULL IDENTITY(1,1),
    [win] BIT NOT NULL,
    [map] VARCHAR(255) NOT NULL,
    [user1] VARCHAR(255) NOT NULL,
    CONSTRAINT [PK__Game__02C72A2DEBE5B9D0] PRIMARY KEY CLUSTERED ([matchID])
);

-- CreateTable
CREATE TABLE [dbo].[Matchup] (
    [matchupID] INT NOT NULL IDENTITY(1,1),
    [heroPlayed] VARCHAR(255) NOT NULL,
    [win] BIT NOT NULL,
    [enemy1] VARCHAR(255) NOT NULL,
    [enemy2] VARCHAR(255) NOT NULL,
    [enemy3] VARCHAR(255) NOT NULL,
    [enemy4] VARCHAR(255) NOT NULL,
    [enemy5] VARCHAR(255) NOT NULL,
    [ally1] VARCHAR(255) NOT NULL,
    [ally2] VARCHAR(255) NOT NULL,
    [ally3] VARCHAR(255) NOT NULL,
    [ally4] VARCHAR(255) NOT NULL,
    [matchID] INT NOT NULL,
    CONSTRAINT [PK__Matchup__E5466D16CF3F8538] PRIMARY KEY CLUSTERED ([matchupID])
);

-- AddForeignKey
ALTER TABLE [dbo].[Matchup] ADD CONSTRAINT [FK__Matchup__matchID__71D1E811] FOREIGN KEY ([matchID]) REFERENCES [dbo].[Game]([matchID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH

